package com.sunrise.monetcafeapplicationapi.enums;

public enum Category {
    CIKOLATA_MUHALLEBI,WAFFLE,PANKEK,LIMONATA,BUBBLE_TEA,SMOOTHIES,COCKTAILS,MILKSHAKE,
    EXPRESSO_BAZLI_SOGUK,EXPRESSO_BAZLI_SICAK,SICAK_ICECEKLER,MESRUBATLAR,
    CAYLAR,EXTRALAR,TURK_KAHVELERI,SPECIAL_ICECEKLER,GELENEKSEL_ICECEKLER
}
